from django.db import models

class SearchModality(models.TextChoices):
    EAD = "ead", "EAD"
    PRESENCIAL = "presencial", "Presencial"
    HIBRIDO = "hibrido", "Híbrido"
    ALL = "all", "Todos"

class SearchStatus(models.TextChoices):
    PENDING = "pending", "Pendente"
    PROCESSING = "processing", "Processando"
    COMPLETED = "completed", "Concluída"
    FAILED = "failed", "Falhou"
    # Novos status para redesign (compatíveis com lowercase existente)
    NO_RESULTS = "no_results", "Sem resultados"
    EXPIRED = "expired", "Expirada"

class SearchArea(models.TextChoices):
    ADMINISTRACAO = "administracao", "Administração"
    AGRARIAS = "agrarias", "Ciências Agrárias"
    BIOLOGICAS = "biologicas", "Ciências Biológicas"
    SAUDE = "saude", "Ciências da Saúde"
    EXATAS = "exatas", "Ciências Exatas e da Terra"
    HUMANAS = "humanas", "Ciências Humanas"
    SOCIAIS = "sociais", "Ciências Sociais Aplicadas"
    ENGENHARIAS = "engenharias", "Engenharias"
    LINGUISTICA_LETRAS_ARTES = "linguistica_letras_artes", "Linguística, Letras e Artes"
    MULTIDISCIPLINAR = "multidisciplinar", "Multidisciplinar"

class SearchStates_Br(models.TextChoices):
    AC = "AC", "Acre"
    AL = "AL", "Alagoas"
    AP = "AP", "Amapá"
    AM = "AM", "Amazonas"
    BA = "BA", "Bahia"
    CE = "CE", "Ceará"
    DF = "DF", "Distrito Federal"
    ES = "ES", "Espírito Santo"
    GO = "GO", "Goiás"
    MA = "MA", "Maranhão"
    MT = "MT", "Mato Grosso"
    MS = "MS", "Mato Grosso do Sul"
    MG = "MG", "Minas Gerais"
    PA = "PA", "Pará"
    PB = "PB", "Paraíba"
    PR = "PR", "Paraná"
    PE = "PE", "Pernambuco"
    PI = "PI", "Piauí"
    RJ = "RJ", "Rio de Janeiro"
    RN = "RN", "Rio Grande do Norte"
    RS = "RS", "Rio Grande do Sul"
    RO = "RO", "Rondônia"
    RR = "RR", "Roraima"
    SC = "SC", "Santa Catarina"
    SP = "SP", "São Paulo"
    SE = "SE", "Sergipe"
    TO = "TO", "Tocantins"