services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  web_consumer:
    build: 
      context: .
      dockerfile: docker/web/Dockerfile
    command: python manage.py consume_search_results
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    restart: always

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    volumes:
      - ./worker:/worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
    restart: always

  scheduler:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: python manage.py run_scheduler
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"


  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"
    restart: always


volumes:
  postgres_data:
