# Generated by Django 5.2.14 on 2026-05-06 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255, verbose_name='Palavras-chave')),
                ('area', models.CharField(blank=True, choices=[('administracao', 'Administração'), ('agrarias', 'Ciências Agrárias'), ('biologicas', 'Ciências Biológicas'), ('saude', 'Ciências da Saúde'), ('exatas', 'Ciências Exatas e da Terra'), ('humanas', 'Ciências Humanas'), ('sociais', 'Ciências Sociais Aplicadas'), ('engenharias', 'Engenharias'), ('linguistica_letras_artes', 'Linguística, Letras e Artes'), ('multidisciplinar', 'Multidisciplinar')], max_length=100, verbose_name='Área do conhecimento')),
                ('modality', models.CharField(blank=True, choices=[('ead', 'EAD'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido'), ('all', 'Todos')], max_length=20, verbose_name='Modalidade')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Requisição de busca',
                'verbose_name_plural': 'Requisições de busca',
                'ordering': ['-created_at'],
            },
        ),
    ]
