# Generated by Django 5.2.14 on 2026-05-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrequest',
            name='error_ref',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Referência de erro'),
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='protocol',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Protocolo'),
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='result_payload',
            field=models.JSONField(blank=True, default=list, verbose_name='Resultados (JSON)'),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluída'), ('failed', 'Falhou'), ('no_results', 'Sem resultados'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
