# Generated by Django 5.2.14 on 2026-06-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchrequest',
            options={'default_manager_name': 'objects', 'ordering': ['-created_at'], 'verbose_name': 'Requisição de busca', 'verbose_name_plural': 'Requisições de busca'},
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluída'), ('failed', 'Falhou'), ('no_results', 'Sem resultados')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
