# Generated by Django 5.2.15 on 2026-06-28 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do alerta')),
                ('keywords', models.CharField(max_length=255, verbose_name='Palavras-chave')),
                ('area', models.CharField(blank=True, choices=[('administracao', 'Administração'), ('agrarias', 'Ciências Agrárias'), ('biologicas', 'Ciências Biológicas'), ('saude', 'Ciências da Saúde'), ('exatas', 'Ciências Exatas e da Terra'), ('humanas', 'Ciências Humanas'), ('sociais', 'Ciências Sociais Aplicadas'), ('engenharias', 'Engenharias'), ('linguistica_letras_artes', 'Linguística, Letras e Artes'), ('multidisciplinar', 'Multidisciplinar')], max_length=100, verbose_name='Área do conhecimento')),
                ('modality', models.CharField(blank=True, choices=[('ead', 'EAD'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido'), ('all', 'Todos')], max_length=20, verbose_name='Modalidade')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('frequency', models.CharField(default='weekly', help_text='Informativo nesta versão; a verificação roda em cadência única.', max_length=20, verbose_name='Frequência')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Última verificação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Alerta salvo',
                'verbose_name_plural': 'Alertas salvos',
                'ordering': ['-created_at'],
            },
        ),
    ]
