# Generated by Django 5.2.15 on 2026-06-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_normalize_status_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedalert',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='course',
            name='modality',
            field=models.CharField(blank=True, choices=[('ead', 'EAD'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='savedalert',
            name='modality',
            field=models.CharField(blank=True, choices=[('ead', 'EAD'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='modality',
            field=models.CharField(blank=True, choices=[('ead', 'EAD'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], max_length=20, verbose_name='Modalidade'),
        ),
    ]
