# Generated by Django 5.2.14 on 2026-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_notification_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='area',
            field=models.TextField(blank=True, default='', help_text='Valores separados por vírgula', verbose_name='Áreas de interesse'),
        ),
    ]
