# Generated by Django 5.2.15 on 2026-06-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_pref_area_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='policy_acceptad',
            field=models.BooleanField(default=False, help_text='Indica se o usuário aceitou a política de privacidade no momento do cadastro', verbose_name='Aceitou a política de Privacidade'),
        ),
    ]
