# Generated by Django 5.2.15 on 2026-06-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_policy_acceptad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='policy_acceptad',
            new_name='policy_accepted',
        ),
    ]
