# Generated by Django 5.2.15 on 2026-07-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notificationsent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_metrics', 'Pode ver o dashboard de métricas')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
