# Generated by Django 5.2.15 on 2026-07-02 16:55

from django.db import migrations

GROUP_NAME = "Analista"
PERM_CODENAME = "view_metrics"


def seed_analista_group(apps, schema_editor):
    """Cria o grupo Analista e concede a ele a permissão de ver as métricas.

    A permissão é obtida via get_or_create porque o sinal post_migrate que
    materializa as permissões (create_permissions) só roda ao fim de todas as
    migrações — dentro da data migration ela pode ainda não existir.
    """
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="core", model="customuser"
    )
    permission, _ = Permission.objects.get_or_create(
        codename=PERM_CODENAME,
        content_type=content_type,
        defaults={"name": "Pode ver o dashboard de métricas"},
    )

    group, _ = Group.objects.get_or_create(name=GROUP_NAME)
    group.permissions.add(permission)


def unseed_analista_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name=GROUP_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_customuser_options"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(seed_analista_group, unseed_analista_group),
    ]
